# Packages
brew 'zsh'
brew 'git'
brew 'rbenv'
brew 'ruby-build'
brew 'vim', args: ['override-system-vi']
brew 'node'
brew 'python'
brew 'brew-cask'
brew 'imagemagick'
brew 'autojump'
brew 'lua'
brew 'luarocks'
brew 'leiningen'

tap 'thoughtbots/formulae'
brew 'pick'

# Apps
tap 'caskroom/cask'

cask 'iterm2'
cask 'google-chrome'
cask 'alfred'
cask 'mjolnir'
cask 'flux'
cask 'shortcat'
cask 'mailbox'
cask 'dropbox'
cask 'mou'
cask 'spotify'
cask 'slack'
cask 'skype'
cask 'tubbler'
cask '1password'
cask 'atom'
cask 'fauxpas'
cask 'evernote'
cask 'dash'
cask 'seil'
cask 'sixtyforce'
cask 'calibre'
cask 'java'
cask 'vlc'

# Quick Look Plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
